version: '3.9'

services:
  db:
    image: postgres:14.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: wordle_collab
      POSTGRES_USER: wordle_collab
      POSTGRES_PASSWORD: wordle_collab
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:6.2-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'

  app:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis
    environment:
      - POSTGRES_HOST=db
      - REDIS_URL=redis://redis:6379/0


volumes:
  postgres-data:
    driver: local