# Generated by Django 5.0 on 2023-12-17 01:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0002_attempt_player_game_attempt_game"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="max_atempts",
            new_name="max_attempts",
        ),
    ]
