# Generated by Django 5.0 on 2023-12-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0004_game_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="status",
            field=models.CharField(
                choices=[
                    ("W", "Waiting"),
                    ("A", "Active"),
                    ("D", "Defeat"),
                    ("V", "Victory"),
                ],
                default="W",
                max_length=1,
            ),
        ),
    ]
