# Generated by Django 5.0 on 2023-12-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0005_alter_game_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="attempt",
            name="hint",
            field=models.CharField(default="", max_length=5),
            preserve_default=False,
        ),
    ]
