# Generated by Django 5.0 on 2023-12-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0006_attempt_hint"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="turn",
            field=models.IntegerField(default=0),
        ),
    ]
